name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Profile Repo
      uses: actions/checkout@v2

    - name: Checkout Private Repo
      uses: actions/checkout@v2
      with:
        repository: your-username/private-repo
        token: ${{ secrets.GH_TOKEN }}

    - name: Fetch Stats
      run: |
        mkdir -p stats
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/your-username/private-repo/stats/contributors > stats/contributors.json
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/your-username/private-repo/languages > stats/languages.json

    - name: Generate Stats
      run: |
        python generate_stats.py

    - name: Update README
      run: |
        cat stats/output.md >> README.md

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with private repo stats"
        git push
