name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow once a day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Profile Repo
      uses: actions/checkout@v2

    - name: Fetch Repositories
      id: fetch-repos
      run: |
        mkdir -p repos
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user/repos?visibility=private > repos.json
        cat repos.json | jq -r '.[] | .full_name' > repos/repo_list.txt

    - name: Fetch Language Stats for Each Repo
      run: |
        mkdir -p stats
        while IFS= read -r repo; do
          repo_sanitized=$(echo $repo | tr / _)
          mkdir -p stats/$repo_sanitized
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/$repo/languages > stats/$repo_sanitized/languages.json
        done < repos/repo_list.txt

    - name: Generate Stats
      run: |
        python generate_stats.py

    - name: Update README
      run: |
        cat stats/output.md > README.md

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with private repo stats"
        git push
